---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: cache
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: cache
spec:
  selector:
    app: cache
  ports:
  - port: 6379
    targetPort: 6379
