---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: frontend
  name: frontend-config
data:
  db_host: "postgres.db.svc"
  redis_host: "redis.cache.svc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: frontend
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/hardy-tine-435523-b0/cbd-ack-2:latest
        ports:
        - containerPort: 80
        env:
        - name: PGDB_USER
          valueFrom:
            secretKeyRef:
              name: frontend-db-secret
              key: pg_username
        - name: PGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frontend-db-secret
              key: pg_password
        - name: PGDB_NAME
          valueFrom:
            secretKeyRef:
              name: frontend-db-secret
              key: db_name
        - name: PGDB_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: db_host
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: redis_host
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: frontend
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
